my_string = input('Input any string: ')
print('Length of your string: ', len(my_string))
print('Your string in capital letters: ', my_string.upper())
print('Your string in lowercase letter: ', my_string.lower())
print('Your string without spaces: ', my_string.replace(' ', ''))
print('First letter of your string: ', my_string[0])
print('Last letter of your string: ', my_string[-1])